---
title: "Build SBML from Sysrev Group Labels"
---

```{r setup, include = FALSE}
library(rsr)       # get sysrev data
library(tidyverse) # tidy data management
library(xml2)      # create sbml / xml documents

# attnode builds lists that xml transform into <tag attr1=... attr2=.../>
attnode <- function(tag, children = list(), ...){list(structure(children, ...)) %>% set_names(tag)}

# function that checks if column exists. If TRUE, returns column. If FALSE, returns NULL
check <- function(x, col){if(col %in% names(x)){x[[col]]}}

# SBOterm named vectors for species, reactions and modifiers 
species_SBOterms <- c(
  "protein" = "SBO:0000252", 
  "receptor" = "SBO:0000244", 
  "ion channel" = "SBO:0000284", 
  "truncated protein" = "SBO:0000252", 
  "gene" = "SBO:0000243", 
  "rna" = "SBO:0000278", 
  "antisense rna" = "SBO:0000334", 
  "phenotype" = "SBO:0000358", 
  "ion" = "SBO:0000327", 
  "simple molecule" = "SBO:0000247", 
  "drug" = "SBO:0000298", 
  "unknown" = "SBO:0000285", 
  "complex" = "SBO:0000253", 
  "degraded" = "SBO:0000291")

reaction_SBOterms <- c(
  "state transition" = "SBO:0000176",
  "known transition omitted" = "SBO:0000395",
  "unknown transition" = "SBO:0000396",
  "transcription" = "SBO:0000183",
  "translation" = "SBO:0000184",
  "transport" = "SBO:0000185",
  "heterofimer association" = "SBO:0000177",
  "dissociation" = "SBO:0000180",
  "truncation" = "SBO:0000178")

modifier_SBOterms <- c(
  "catalysis" = "SBO:0000013",
  "unknown catalysis" = "SBO:0000462",
  "inhibition" = "SBO:0000537",
  "unknown inhibition" = "SBO:0000536",
  "physical stimulation" = "SBO:0000459",
  "modulation" = "SBO:0000594",
  "trigger" = "SBO:0000461")
```

sysrev.com/p/109491 has `listOfCompartments` `listOfSpecies` `listOfReactions` labels.
```{r write sbml}
# write sbml from sbtab-label tables - output is xml_document as per the xml2 package 
write_sbml <- function(pid, aid, srToken){
  # get project compartment species and reaction tables from Sysrev
  atbls <- rsr::get_answers_list(pid, srToken)
  
  # filter project on single paper
  atbls <- atbls %>% lapply(function(x){x[which(x["aid"] == aid),]})

  # listOfCompartments - compartments have [metaid, id, size, units]
  listOfCompartments <- atbls$Compartment %>% 
    select(metaid = ID, id = ID, size = Size, name = Name, units = Unit) %>% 
    distinct() %>%
    pmap(~attnode("compartment", ...)) %>%
    flatten()
  
  # listOfSpecies - species have [metaid id name compartment initialAmount]
  # reformat types and fill empty spots 
  atbls$Compound$Type <- atbls$Compound$Type %>% tolower() %>% str_replace_all("_", " ")
  atbls$Compound$Type[which((atbls$Compound$Type == "")|(is.null(atbls$Compound$Type)))] <- "simple molecule"
  # create listofcompounds 
  listOfSpecies <- atbls$Compound %>%
    # switch type names to SBOterms
    mutate(sboTerm = str_replace_all(Type, species_SBOterms)) %>%
    select(metaid = ID, 
           id = ID, 
           name = Name, 
           compartment = Location, 
           initialAmount = InitialConcentration, 
           sboTerm) %>% 
    distinct() %>% 
    pmap(~attnode("species", ...)) %>%
    flatten()
  
  # individual reactions for listOfReactions
  # seperate the reaction formulas into two columns 
  ## this option can be dropped if the table format in Sysrev/Phymdos is changed from 'ReactionFormula' to 'reactant' and 'product'
  if("ReactionFormula" %in% names(atbls$Reaction)){
      reactions <- atbls$Reaction %>%
        separate(ReactionFormula, into = c("Reactants", "Products"), sep = "<=>")
      }else{
          reactions <- atbls$Reaction
      }
  
  # check if table contains ModifierType column and fill empty cells in ModifierType 
  reactions <- if(is.null(check(reactions, "ModifierType"))){reactions %>% mutate(ModifierType = "")
  }else{reactions %>% mutate(ModifierType = {tolower(ModifierType) %>% str_replace_all("_", " ")})}
  reactions$ModifierType[which((reactions$ModifierType == "")|(is.null(reactions$ModifierType)))] <- "catalysis"
  # create rest of elements
  reactions <- reactions %>% 
    mutate(sboTerm = str_replace_all(ModifierType, modifier_SBOterms)) %>%
    # Select the necesary columns, remove duplicates and arrange by id 
    ## arranging is necesary because of the overlap with listOfReactions
    select(id = ID, 
           listOfReactants = Reactants,
           listOfProducts = Products,
           listOfModifiers = Modifier,
           sboTerm) %>% 
    distinct() %>%
    arrange(id) %>%
    # Change format of the table so reactions can get a unique metaid, also group by id and split into list
    pivot_longer(cols = c("listOfReactants","listOfProducts", "listOfModifiers"), 
                 names_to = "type", 
                 values_to = "species") %>%
    cbind(metaid = paste0("CDMT", 1:nrow(.))) %>% 
    mutate(species = trimws(species)) %>% 
    group_by(id) %>% 
    group_split() %>% 
    # Separate reactions into SBML formatted list
    lapply(function(x){
       apply(x[3], 1, function(y){
         lapply(y, function(z){
           if(z == "listOfModifiers"){
             x[which(x[3] == z),] %>% 
             select(metaid, species, sboTerm) %>%
             pmap(~attnode("modifierSpeciesReference",...)) %>% 
             flatten()
           }else{
             x[which(x[3] == z),] %>% 
             select(metaid, species) %>%
             pmap(~attnode("speciesReference",...)) %>% 
             flatten()
           }
         })
       }) %>% 
       flatten() %>%
       set_names(x[[3]])
    }) %>%
    set_names(pull(arrange(distinct(select(atbls$Reaction, ID)), ID)))
  
  # listOfReactions - reactions have [metaid id reversible]
  # reformat types and fill empty spots 
  atbls$Reaction$Type <- atbls$Reaction$Type %>% tolower() %>% str_replace_all("_", " ")
  atbls$Reaction$Type[which((atbls$Reaction$Type == "")|(is.null(atbls$Reaction$Type)))] <- "state transition"
  # create listofreactions 
  listOfReactions <- atbls$Reaction %>%
    mutate(`IsReversible?` = tolower(`IsReversible?`), 
           sboTerm = str_replace_all(Type, reaction_SBOterms)) %>%
    select(metaid = ID, id = ID, reversible = `IsReversible?`, sboTerm) %>%
    distinct() %>%
    arrange(id) %>%
    pmap(~attnode("reaction", ..., children = flatten(reactions[.]))) %>%
    flatten()

  # write final model and include isolated nodes 
  model <- attnode(tag = "model", metaid = "documentname", id = "documentname",
                   children = lst(listOfCompartments, listOfSpecies, listOfReactions))
  sbml.root <- attnode(tag = "sbml", xmlns = "http://www.sbml.org/sbml/level2/version4", level = 2, version = 4,
                      children = model)
  sbml_model <- as_xml_document(sbml.root)
  return(sbml_model)
}
```

```{r write sbtab}
# create sbtab tables from sbml file
write_sbtab <- function(sbml){
  # create list from sbml
  tablist <- as_list(sbml)

  # create empty tables for Compound, Compartment, Reaction and individual reactions
  Compartment <- tibble()
  Compound <- tibble()
  Reaction <- tibble()
  reaction_compounds <- tibble(Reactant = as.character(1:length(tablist[[1]][[1]][["listOfReactions"]])), Product = "", Modifier = "", ModifierType = "")

  # convert compartments to table
  for(i in 1:length(tablist[[1]][[1]][["listOfCompartments"]])){
    Compartment <- rbind(Compartment, as_tibble(attributes(tablist[[1]][[1]][["listOfCompartments"]][[i]])))
  }
  # correct column names
  Compartment <- Compartment %>% 
    transmute(
      "ID" = check(., "id"), 
      "Name" = check(., "name"), 
      "Size" = check(., "size"), 
      "Unit" = check(., "units"), 
      "OuterCompartment" = check(., "outside"))
  
  # convert compartments to table
  for(i in 1:length(tablist[[1]][[1]][["listOfSpecies"]])){
    Compound <- rbind(Compound, as_tibble(attributes(tablist[[1]][[1]][["listOfSpecies"]][[i]])))
  }

  # correct column names
  Compound <- Compound %>% transmute(
                        "ID" = check(., "id"), 
                        "Name" = check(., "name"), 
                        "Type" = if(is.null(check(., "sboTerm"))){
                          NULL
                          }else{
                            str_replace_all(sboTerm, setNames(names(compound_SBOterms), compound_SBOterms))
                            },
                        "InitialValue" = check(., "initialAmount"), 
                        "Unit" = check(., "units"), 
                        "Location" = check(., "compartment"), 
                        "IsConstant" = check(., "constant"), 
                        "HasOnlySubstanceUnits" = check(., "hasOnlySubstanceUnits"))
  
  # convert Reactions to table
  for(i in 1:length(tablist[[1]][[1]][["listOfReactions"]])){
    # get reactions
    Reaction <- rbind(Reaction, as_tibble(attributes(tablist[[1]][[1]][["listOfReactions"]][[i]])))
    for(c in 1:length(tablist[[1]][[1]][["listOfReactions"]][[i]])){
      # get reactants and ModifierType SBOterms
      reaction_compounds[i,c] <- 
        attributes(tablist[[1]][[1]][["listOfReactions"]][[i]][[c]][[1]])[["species"]]
      if(is.null(check(attributes(tablist[[1]][[1]][["listOfReactions"]][[i]][[c]][[1]]), "sboTerm"))==FALSE){
        reaction_compounds[i,"ModifierType"] <-
          attributes(tablist[[1]][[1]][["listOfReactions"]][[i]][[c]][[1]])[["sboTerm"]]
      }
    }
  }
  # bind reactants to reactions
  Reaction <- Reaction[-1] %>% distinct() %>% cbind(reaction_compounds)
  
  # correct Reaction names
  Reaction <- Reaction %>% 
    transmute(
      "ID" = check(., "id"), 
      "Name" = check(., "name"), 
      "Type" = if(is.null(check(., "sboTerm"))){
        NULL
        }else{
          str_replace_all(sboTerm, setNames(names(reaction_SBOterms), reaction_SBOterms))
          },
      "IsReversible" = check(., "reversible"),
      Reactant,
      Product,
      Modifier,
      "ModifierType" = if(is.null(check(., "ModifierType"))){
        NULL
        }else{
          str_replace_all(ModifierType, setNames(names(modifier_SBOterms), modifier_SBOterms))
          },
      "Location" = check(., "location"), 
      "KineticLaw" = check(., "kineticLaw"))
  
  sbtab <- list("Compartment"= Compartment, "Compound" = Compound, "Reaction" = Reaction)
  return(sbtab)
}
```

```{r usage}
# sysrev to celldesigner project compartment species and reaction tables
token <- rstudioapi::askForSecret("sysrev token w/ ontox access")
atbls <- rsr::get_answers_list(117883, token = token)

# write sbml
sbml <- write_sbml(117883, 14352862, token)

# print the sbml to consle
cat(toString(sbml))

# print the xml to a file 
write_xml(sbml, "srtest2.xml")

# write sbml to sbtab tables
#sbtabs <- 
  write_sbtab(sbml)
```





